#!/usr/bin/env python3
from __future__ import annotations

import argparse
from collections import defaultdict
from pathlib import Path

from _llm_wiki_common import Record, records, relative_link, table_cell, work_metadata


# Preserve the v1 marker so an implementation-only refactor does not drift every existing Wiki.
GENERATED = "<!-- generated by knowledge_index.py; do not edit -->"


def _wiki_table(items: list[Record], target: Path) -> list[str]:
    lines = ["| Title | Summary | Status | Note |", "|---|---|---|---|"]
    for item in items:
        lines.append(
            "| {title} | {summary} | {status} | [{path}]({link}) |".format(
                title=table_cell(item.metadata.get("title") or item.relative.stem),
                summary=table_cell(item.metadata.get("summary")),
                status=table_cell(item.metadata.get("status")),
                path=item.relative.as_posix(),
                link=relative_link(target, item.path),
            )
        )
    if not items:
        lines.append("| _None_ |  |  |  |")
    return lines


def _source_table(items: list[Record], target: Path) -> list[str]:
    lines = ["| Title | Type | Storage | Captured | Source |", "|---|---|---|---|---|"]
    for item in items:
        lines.append(
            "| {title} | {type} | {storage} | {captured} | [{path}]({link}) |".format(
                title=table_cell(item.metadata.get("title") or item.relative.stem),
                type=table_cell(item.metadata.get("source_type")),
                storage=table_cell(item.metadata.get("storage")),
                captured=table_cell(item.metadata.get("captured")),
                path=item.relative.as_posix(),
                link=relative_link(target, item.path),
            )
        )
    if not items:
        lines.append("| _None_ |  |  |  |  |")
    return lines


def _state_table(root: Path, target: Path) -> list[str]:
    lines = ["| Title | Stage | Updated | State |", "|---|---|---|---|"]
    states = sorted((root / "state").glob("*.md")) if (root / "state").is_dir() else []
    for path in states:
        metadata = work_metadata(path)
        lines.append(
            "| {title} | {stage} | {updated} | [{path}]({link}) |".format(
                title=table_cell(metadata.get("title") or path.stem),
                stage=table_cell(metadata.get("단계")),
                updated=table_cell(metadata.get("갱신")),
                path=path.relative_to(root).as_posix(),
                link=relative_link(target, path),
            )
        )
    if not states:
        lines.append("| _None_ |  |  |  |")
    return lines


def _domain_indexes(root: Path, section: str, items: list[Record]) -> dict[Path, str]:
    grouped: dict[str, list[Record]] = defaultdict(list)
    for item in items:
        parts = item.relative.parts
        domain = parts[1] if len(parts) > 2 else "_root"
        grouped[domain].append(item)

    section_root = root / section
    domains = set(grouped)
    if section_root.is_dir():
        domains.update(path.name for path in section_root.iterdir() if path.is_dir())

    generated: dict[Path, str] = {}
    for domain in sorted(domains):
        if domain == "_root":
            continue
        members = grouped.get(domain, [])
        target = root / section / domain / "index.md"
        table = _wiki_table(members, target) if section == "wiki" else _source_table(members, target)
        title = f"# {domain} {section.title()} Index"
        generated[target] = "\n".join([title, "", GENERATED, "", *table, ""])
    return generated


def generated_indexes(root: Path, project: bool = False) -> dict[Path, str]:
    wiki = records(root, "wiki")
    sources = records(root, "sources")
    root_index = root / "index.md"
    wiki_index = root / "wiki/index.md"
    source_index = root / "sources/index.md"
    root_lines = ["# Project Index" if project else "# Knowledge Index", "", GENERATED, ""]
    if project:
        root_lines.extend(["## Active Work", "", *_state_table(root, root_index), ""])
    root_lines.extend(
        ["## Wiki", "", *_wiki_table(wiki, root_index), "", "## Sources", "", *_source_table(sources, root_index), ""]
    )
    result = {
        root_index: "\n".join(root_lines),
        wiki_index: "\n".join(["# Wiki Index", "", GENERATED, "", *_wiki_table(wiki, wiki_index), ""]),
        source_index: "\n".join(
            ["# Sources Index", "", GENERATED, "", *_source_table(sources, source_index), ""]
        ),
    }
    result.update(_domain_indexes(root, "wiki", wiki))
    result.update(_domain_indexes(root, "sources", sources))
    return result


def update_indexes(root: Path, check: bool, project: bool = False) -> list[Path]:
    drift: list[Path] = []
    for path, expected in generated_indexes(root, project=project).items():
        current = path.read_text(encoding="utf-8") if path.is_file() else None
        if current == expected:
            continue
        drift.append(path)
        if not check:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    return drift


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate deterministic LLM Wiki indexes.")
    parser.add_argument("repository", type=Path)
    parser.add_argument("--check", action="store_true", help="Report drift without writing.")
    parser.add_argument("--project", action="store_true", help="Include project active-work routing.")
    args = parser.parse_args()
    root = args.repository.resolve()
    if not root.is_dir():
        parser.error(f"repository does not exist: {root}")

    drift = update_indexes(root, args.check, project=args.project)
    for path in drift:
        action = "DRIFT" if args.check else "UPDATED"
        print(f"{action} {path.relative_to(root)}")
    if not drift:
        print("OK indexes are current")
    return 1 if args.check and drift else 0


if __name__ == "__main__":
    raise SystemExit(main())
